import {
  ArrowRight,
  Banknote,
  Bell,
  Briefcase,
  Calendar,
  ChevronDown,
  CircleCheck,
  CreditCard,
  FileText,
  LayoutDashboard,
  Link2,
  Lock,
  LogOut,
  Menu,
  Moon,
  Settings,
  Shield,
  Sun,
  UserCheck,
  UserPlus,
  Users,
  Wallet,
} from 'lucide-angular';

// Set curado de icones Lucide do New Design System SEP (atalhos, jornadas,
// navegacao, header). Registrado uma vez via `LucideAngularModule.pick` em
// `app.config`; as telas consomem por nome, ex.: `<lucide-icon name="users">`.
export const LUCIDE_ICONS = {
  ArrowRight,
  Banknote,
  Bell,
  Briefcase,
  Calendar,
  ChevronDown,
  CircleCheck,
  CreditCard,
  FileText,
  LayoutDashboard,
  Link2,
  Lock,
  LogOut,
  Menu,
  Moon,
  Settings,
  Shield,
  Sun,
  UserCheck,
  UserPlus,
  Users,
  Wallet,
};
