// Nome curto de cada roteiro quando ele aparece como submodulo no cartao do "Modulo completo". O titulo
// inteiro ("Contratos e parcelas dos clientes") enchia o cartao de fichas truncadas: com o nome curto, as
// fichas de qualquer modulo cabem em duas linhas e o cartao fica do mesmo tamanho em todos.
// A chave e o id do roteiro; sem entrada, vale o titulo.
export const ROTULO_SECAO: Record<string, string> = {
  'backoffice-visao-geral': 'Dashboard',
  'backoffice-indicadores': 'Indicadores',
  'backoffice-fila': 'Fila',
  'backoffice-tratar': 'Tratar',
  'backoffice-reprocessos': 'Histórico',
  'backoffice-reprocessar': 'Reprocesso',
  'cobranca-visao-geral': 'Visão geral',
  'cobranca-agenda-contrato': 'Agenda do contrato',
  'cobranca-agenda-financeira': 'Agenda',
  'cobranca-inadimplencia': 'Inadimplência',
  'cobranca-parcela': 'Parcela',
  'cobranca-renegociacao': 'Renegociação',
  'correspondentes-painel': 'Painel',
  'correspondentes-contratos': 'Contratos',
  'correspondentes-base': 'Base',
  'correspondentes-documentos': 'Documentos',
  'correspondentes-prospeccao': 'Funil',
  'correspondentes-agenda': 'Agenda',
  'correspondentes-comissoes': 'Comissões',
  'correspondentes-desempenho': 'Desempenho',
  'correspondentes-relatorios': 'Relatórios',
  'correspondentes-rede': 'Rede',
  'correspondentes-comissionamento': 'Comissionamento',
  'correspondentes-desempenho-rede': 'Desempenho da rede',
  'correspondentes-auditoria': 'Auditoria',
  'correspondentes-validacao': 'Validação',
  'credito-visao-geral': 'Visão geral',
  'credito-propostas': 'Propostas',
  'credito-nova': 'Nova proposta',
  'credito-acompanhar': 'Acompanhar',
  'credora-visao-geral': 'Visão geral',
  'credora-cadastro': 'Cadastro',
  'credora-perfil': 'Perfil',
  'credora-oportunidades': 'Oportunidades',
  'credora-carteira': 'Carteira',
  'formalizacao-visao-geral': 'Visão geral',
  'formalizacao-contrato': 'Contrato',
  'formalizacao-aceite': 'Aceite',
  'onboarding-visao-geral': 'Visão geral',
  'onboarding-pessoa': 'Pessoa física',
  'onboarding-empresa': 'Empresa',
  'parametros-catalogo': 'Catálogo',
  'parametros-consultar': 'Consultar',
  'parametros-alterar': 'Alterar',
  'perfil-conta': 'Conta',
  'perfil-senha': 'Senha',
  'perfil-totp': 'TOTP',
  'pix-visao-geral': 'Visão geral',
  'pix-desembolsos': 'Desembolsos',
  'pix-solicitar-desembolso': 'Solicitar',
  'pix-recebimentos': 'Recebimentos',
  'pix-divergencias': 'Divergências',
  'plataforma-menu': 'Menu',
  'plataforma-topo': 'Topo',
  'plataforma-conta': 'Conta',
  'publico-inicio': 'Início',
  'publico-login': 'Login',
  'publico-credito-pj': 'Crédito PJ',
  'publico-seguranca': 'Segurança',
  'publico-como-funciona': 'Como funciona',
  'publico-sobre': 'Sobre',
  'publico-contato': 'Contato',
  'publico-privacidade': 'Privacidade',
  'publico-termos': 'Termos',
  'usuarios-visao-geral': 'Lista',
  'usuarios-incluir': 'Incluir',
  'usuarios-editar': 'Editar papéis',
  'usuarios-excluir': 'Excluir',
};
